server:
  port: 11000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hct
    url: jdbc:mysql://192.168.36.128:3306/gulimall_wms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-wms

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto